### ISSUE TITLE
Registration page refers to "Data Carpentry" instead of "Data Commons"

### ISSUE THREAD

**Issue by mmtrun** [dcppc/2018-september-workshop#1]
The registration page

[https://ti.to/dcppc/september-dcppc-workshop](https://ti.to/dcppc/september-dcppc-workshop)

has a subtitle "Data _Carpentry_ Pilot Phase Consortium". This should read "Data Commons Pilot Phase Consortium".

**Comment by charlesreid1** [comment]
Freudian slip... Thanks for pointing this out! :)

**Comment by raynamharris** [comment]
Thanks @mmtrun! I've corrected the mistake.
