### ISSUE TITLE
FISMA Compliance for Data Commons Developers

### ISSUE THREAD

**Issue by kevinwilson** [dcppc/2018-september-workshop#12]
We would like to propose a breakout session to discuss FISMA compliance and the activities that developers need to complete to ensure a successful authority to operate in phase 2. In this session, we will describe the key NIST technical controls that must be implemented by commons systems and engage developers in a discussion of implementation strategies.

Room: Conference room - 10 people

Target audience: Data commons developers and project managers

Connection information for remote participants:

Join from PC, Mac, Linux, iOS or Android: https://renci.zoom.us/j/518234245

Or iPhone one-tap :
    US: +16699006833,,518234245#  or +16465588656,,518234245# Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 669 900 6833  or +1 646 558 8656  or +1 877 853 5257 (Toll Free) or +1 855 880 1246 (Toll Free)
    Meeting ID: 518 234 245
    International numbers available: https://zoom.us/u/adEcqBM51S

**Comment by davidbernick** [comment]
What time will this be at so I can make sure I go?

**Comment by kevinwilson** [comment]
Hi David - I believe 13:00 to 16:00.

**Comment by davidbernick** [comment]
oh and which day?

**Comment by kevinwilson** [comment]
Requested for the first day, 9/20.

**Comment by kevinwilson** [comment]
@raynamharris can we switch this presentation to 9/20 and move the logging one to 9/21?

**Comment by raynamharris** [comment]
new zoom room https://zoom.us/j/558817992
